title: MOREL
description: obras latinoamericanas de dominio público
permalink: /:categories/:year/:month/:day/:title:output_ext
img: logo.png
background: trama.png

author : 
  name : MOREL
  site: https://morel.la
  description : Metadatos de Obras para Repositorios Electrónicos Latinoamericanos impulsa la creación de archivos digitales de libre acceso.
  image : avatar.png
  email : proyectomorel@gmail.com
  github : 
  twitter : 
  instagram: morelrep

collections:
  cities:
    output: true
    permalink: /cities/:name
  books:
    output: true
    permalink: /obras/:name
  authors:
    output: true
    permalink: /authors/:name
  publishers:
    output: true
    permalink: /publishers/:name
  repositories:
    output: true
    permalink: /repositorios/:name
  periods:
    output: true 
    permalink: /periodos/:name
  chriterias:
    output: true
    permalink: /criterios/:name

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "cities"
    values:
      layout: "city"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "repositories"
    values:
      layout: "repository"

theme: morel-theme